### ISSUE TITLE
Hello, sir, I have the following problem after running

### ISSUE THREAD

**Issue by xsk0802** [kevinoop0/WaveCT-AIN_base_version#1]
Namespace(content='./examples/content', image_size=512, option_unpool='cat5', output='./outputs/', style='./examples/style', transfer_all=False, transfer_at_decoder=True, transfer_at_encoder=False, transfer_at_skip=False, verbose=True)
  0%|                                                                       | 0/2 [00:00<?, ?it/s]------ transfer: ./outputs/1.png
transfer at decoder 4
transfer at decoder 3
transfer at decoder 2
transfer at decoder 1
Elapsed time in whole WCT: 0:00:02.243419
 50%|███████████████████████████████▌                               | 1/2 [00:05<00:05,  5.66s/it]------ transfer: ./outputs/2.png
Elapsed time in whole WCT: 0:00:00.103988
 50%|███████████████████████████████▌                               | 1/2 [00:05<00:05,  5.77s/it]
Traceback (most recent call last):
  File "transfer.py", line 174, in <module>
    run_bulk(config)
  File "transfer.py", line 137, in run_bulk
    img = wct.transfer(content, style)
  File "transfer.py", line 68, in transfer
    style_feats, style_skips = self.get_all_feature(style)
  File "transfer.py", line 54, in get_all_feature
    x = self.encode(x, skips, level)
  File "transfer.py", line 45, in encode
    return self.encoder.encode(x, skips, level)
  File "/home/ps/xushaokang/WaveCT-AIN_base_version-main/model.py", line 164, in encode
    out = self.conv0(x)
  File "/home/ps/xushaokang/registration_env/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1190, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/ps/xushaokang/registration_env/lib/python3.8/site-packages/torch/nn/modules/conv.py", line 463, in forward
    return self._conv_forward(input, self.weight, self.bias)
  File "/home/ps/xushaokang/registration_env/lib/python3.8/site-packages/torch/nn/modules/conv.py", line 459, in _conv_forward
    return F.conv2d(input, weight, bias, self.stride,

RuntimeError: Given groups=1, weight of size [3, 3, 1, 1], expected input[1, 1, 512, 512] to have 3 channels, but got 1 channels instead

**Comment by kevinoop0** [comment]
It needs 3 channels, you can change the input (e.g. copy 3 times across the channel direction) or modify the model.
